default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= Rails.application.credentials.dig(:database, :password) %>
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: car_adverstiments_web_development

test:
  <<: *default
  database: car_adverstiments_web_test

production:
  <<: *default
  database: car_adverstiments_web_production
