name: Lintering and Deploying

on:
  - push
  - pull_request

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        gemfile:
          - Gemfile
        ruby:
          - '3.1.0'
    runs-on: ${{ matrix.os }}
    env:
      - BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundle-cache: true
      - run: bundle exec lefthook run pre-commit
      - run: bundle exec rspec
