name: Lintering and Deploying

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby:
          - '3.1.0'
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: "kerfi10dima"
          POSTGRES_DB: car_adverstiments_web_development
        ports:
          - 5432:5432
        options: >-
          --mount type=tmpfs,destination=/var/lib/postgresql/data
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Install PostgreSQL
        run: sudo apt-get -yqq install libpq-dev
      - name: Run bundle install
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Setup database schema
        run: bin/rails db:create db:scheme:load
      - name: Run tests
        run: bundle exec rspec

  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby:
          - '3.1.0'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Call config lefthook 
        run: bin/bundle exec lefthook run pre-commit
















      # - run: bundle exec rspec
      # - run: bundle exec lefthook run pre-commit
